### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-buscadores-de-datos#1]
* Roldan Uriel Arcadio Avila
* Pedro Garcia Garcia
* Ariadna Monserrat Lopez Aparicio
[Reporte de La entrevista.pdf](https://github.com/user-attachments/files/17612167/Reporte.de.La.entrevista.pdf)

**Comment by EdgarExa** [comment]
28 de 30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Felicidades...
